global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'processing_service'
    static_configs:
      - targets: ['processing_service:8000']

  - job_name: 'ingestion_service'
    static_configs:
      - targets: ['ingestion_service:8001']

  - job_name: 'analytics_service'
    static_configs:
      - targets: ['analytics_service:8002']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']