version: '3.8'

networks:
  fsa_network:
    driver: bridge

services:
  base:
    build:
      context: ./app
      dockerfile: base.Dockerfile
    image: fsa-base:latest

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fsa_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - fsa_network

  clickhouse:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./migrations/clickhouse/clickhouse_init.sql:/docker-entrypoint-initdb.d/clickhouse_init.sql
      - ./migrations/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    networks:
      - fsa_network
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    environment:
      CLICKHOUSE_DB: analytics_db
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsa_parser_db
    ports:
      - "5437:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fsa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d

  ingestion_service:
    build:
      context: ./app/ingestion_service
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONPATH=/app
    networks:
      - fsa_network

  processing_service:
    build:
      context: .
      dockerfile: ./app/processing_service/Dockerfile
    depends_on:
      base:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ./app/common:/app/common
      - ./app/processing_service:/app/processing_service
      - ./logs:/app/logs:rw
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsa_parser_db
    command: dockerize -wait tcp://kafka:29092 -wait tcp://postgres:5432 -wait tcp://clickhouse:8123 -timeout 300s python main.py
    user: root
    restart: on-failure
    networks:
      - fsa_network

  analytics_service:
    build:
      context: .
      dockerfile: ./app/analytics_service/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8002:8002"
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsa_parser_db
    command: ["dockerize", "-wait", "tcp://clickhouse:8123", "-wait", "tcp://postgres:5432", "-timeout", "300s", 
              "uvicorn", "analytics_service.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload", "--log-level", "info"]
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - fsa_network
    restart: on-failure

volumes:
  clickhouse_data:
  clickhouse_logs:
  postgres_data:
